name = "inventory-software"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "inventory-software"
database_id = "c3915cab-2b6f-4643-8426-4eca10c7c9ac"
migrations_dir = "prisma/migrations"

